[package]
name = "synctui-resolver"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.56", features = ["derive"] }
crossterm = "0.29.0"
ratatui = "0.30.0"
walkdir = "2.5.0"

[dev-dependencies]
tempfile = "3.24.0"
